/// Flutter icons ExtraTechIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExtraTechIcons
///      fonts:
///       - asset: fonts/ExtraTechIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExtraTechIcons {
  ExtraTechIcons._();

  static const _kFontFam = 'ExtraTechIcons';
  static const _kFontPkg = null;

  static const IconData flutter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData witai = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kivy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sqlite = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
